---
#
##
### Written by Maxence Maireaux (maxence.maireaux@wescale.fr)
##
#
- hosts: localhost
  become: no
  vars:
    include_dir: "{{ playbook_dir }}/inc"

  pre_tasks:
    - include_tasks: "{{ include_dir }}/_init.yml"
    - include_tasks: "{{ include_dir }}/{{ osf_provider }}/_init.yml"
    - include_tasks: "{{ include_dir }}/_ansible_dependencies.yml"

  tasks:
    - include_tasks: "{{ include_dir }}/{{ osf_provider }}/_packer_build.yml"
    - include_tasks: "{{ include_dir }}/{{ osf_provider }}/_get_ami.yml"

  post_tasks:
    - name: "Build success - awesomeness, joy, that sort of feelings"
      debug:
        msg: >-
          Image build is a success. Your AMI : {{ ami_id }}
